### ISSUE TITLE
Not working on array of scss files

### ISSUE THREAD

**Issue by gatilin222** [tomgrooffer/gulp-sass-glob#15]
If I push to gulp 1 file it's works well, but if I push array of files it's broken.
```
// works
gulp.task('sass', function () {
	gulp.src([assetsDir + 'sass/_includes.scss'])
		.pipe(plumber())
		.pipe(sassGlob())
		.pipe(sass())
		.pipe(gulp.dest(outputDir + 'styles/'))
});
// not
gulp.task('sass', function () {
	gulp.src([assetsDir + 'sass/**/*.scss'])
		.pipe(plumber())
		.pipe(sassGlob())
		.pipe(sass())
		.pipe(gulp.dest(outputDir + 'styles/'))
});
```
` messageOriginal: File to import not found or unreadable: blocks/**/*.scss`

**Comment by willans** [comment]
I get the same as @gatilin222

**Comment by bradallenfisher** [comment]
same here.

**Comment by tomgrooffer** [comment]
on it

**Comment by tomgrooffer** [comment]
@gatilin222 @willans @bradallenfisher the problem occurs when you have "glob" import statements in nested imports, this is currently unsupported. What I suggest is only point your gulp to 1 file i.e. "main.scss" -> then ONLY in that main.scss you use glob imports, not nested. 

I hope this helps enough, and I hope you can resolve your problem by thinking this way.

**Comment by tomgrooffer** [comment]
@gatilin222 @willans @bradallenfisher I have updated the read me to explain it in a better way. [Check it out.](https://github.com/tomgrooffer/gulp-sass-glob/#nested-glob-imports)

**Comment by bradallenfisher** [comment]
Hey thanks for looking at this. I think the real problem is that in your gulp.task you have to be explicit as to what file is going to hold ALL your @import statements. The nested @import statements work fine if you do. I think what we were hoping for is that you don't have to specifically point to one file as the source of all your imports. 
I'm not sure the README was updated to really reflect the problem since it's more about correcting and "issue" with your gulp file not the main.scss file.

**Comment by danbohea** [comment]
@bradallenfisher Agreed. Just arrived here after looking for an issue that discussed wildcards in `src` parameters.

It seems that specifying a single Sass file where there's globbing in @imports works as expected. Using wildcards to indicate which Sass files may include globbed @imports leads to errors.

I've not used nested glob @imports anywhere so I think this issue is confusing 2 different problems.

### Examples

**Works as expected:**

```
gulp.task('sass', function () {
  gulp.src('src/sass/main.scss') // specifying single scss file
    .pipe(sassGlob())
    .pipe(sass())
    .pipe(gulp.dest('./dist/css'))
});
```

**Results in errors:**

```
gulp.task('sass', function () {
  gulp.src('./src/sass/*.scss') // specifying multiple possible scss files
    .pipe(sassGlob())
    .pipe(sass())
    .pipe(gulp.dest('./dist/css'))
});
```

Can we re-open this?

**Comment by danbohea** [comment]
Deleted my previous comment as it turns out I did have a nested glob @import that I just wasn't aware of!
