### ISSUE TITLE
Consider going back to using releases on GH

### ISSUE THREAD

**Issue by jrencz** [tomgrooffer/gulp-sass-glob#18]
It's easier to keep track of what happens when releases are in sync with what happens on NPM: https://github.com/tomgrooffer/gulp-sass-glob/releases

**Comment by Nirazul** [comment]
Just now, I've stumbled upon the problem when `gulp-sass-glob` chokes on empty directories.
This issue was closed in #22 

As there is no release history, I have no chance of knowing if this error is present in `1.0.6.`.

So GH releases would be very helpful, especially combined with a short changelog.

**Comment by jpt** [comment]
@Nirazul I just came to the same conclusion as you, after running into the same old bug.

For the time being it would be nice if the npm registry were updated to include 1.0.7., so that my package.json could simply say `"gulp-sass-glob": "^1.0.7"` instead of `"gulp-sass-glob": "git+https://github.com/tomgrooffer/gulp-sass-glob.git"`

**Comment by Nirazul** [comment]
@jpt For the time being you can also use [`gulp-sass-glob-2`](https://www.npmjs.com/package/gulp-sass-glob-2). It has been added to the registry for this exact reason by @DanielaValero

**Comment by tomgrooffer** [comment]
@DanielaValero I have send you and invite for collab. Very nice you duplicated the package.
