### ISSUE TITLE
Control order of globbing partials?

### ISSUE THREAD

**Issue by sensaetions** [tomgrooffer/gulp-sass-glob#27]
Hello, I'm aware that files are automatically alphabetically sorted before being imported.

Is there any way for us to be able to control how the order of sorting? I ask because there are times when global styling should be declared before unique selector styling. But with auto alphabetizing, the global styles can be meshed up in the middle of the ordering.

If this is not possible with sass globbing, are there workarounds? For example, are there file naming structures that you'd recommend so that the ordering could somewhat be controlled (such as including numbers), with global styles rendering first?

**Comment by Nirazul** [comment]
As of my knowledge there is no such possibility in the library.
I think you can satisfy your needs easily by using a folder pattern.

Consider this as the status quo:
```
@import 'files/util/reset';
@import 'files/util/typo';
@import 'files/modules/navbar';
@import 'files/modules/button';
```

Easily done with `gulp-sass-glob`...
```
@import 'files/**';
```

Whoops, now the modules folder is imported before the util folder. We don't want that! Due to the nature of the plugin, every glob is interpreted independently. So we can just use two consecutive globs instead of one:

```
@import 'files/util/**';
@import 'files/modules/**';
```

When it comes to file ordering within the util or modules folder, I don't think it's a good practice to depend on a strict order. As general utility styles don't change that often, I'm using the plugin only for modules and my `function`, `mixin` and `extend` libraries.

**Comment by sensaetions** [comment]
Ok, thanks for your reply. Since there's no way to control the strict order of sass partials using globbing, maybe I need to reconsider a different organization method that will allow me to order them based on hierarchy.
